# Generated by Django 2.2.5 on 2019-09-27 05:47

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='UrlShortner',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('shorted_url', models.URLField()),
                ('original_url', models.URLField(max_length=1000)),
                ('created', models.DateTimeField(auto_now=True)),
            ],
        ),
    ]
