# Generated by Django 2.2.5 on 2019-09-27 06:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('url', '0002_auto_20190927_1225'),
    ]

    operations = [
        migrations.AlterField(
            model_name='urlshortner',
            name='email',
            field=models.EmailField(default='None@gmail.com', max_length=254),
        ),
    ]
